### Create a new user
POST http://localhost:3000/users/signup
content-type: application/json

{
  "email": "Nag@test.com",
  "password": "123456"
}


### Find a particular user with a given ID
GET http://localhost:3000/users/3


### Find all users with a given email
GET http://localhost:3000/users?email=test@test.com

### Delete a user given id
DELETE http://localhost:3000/users/1


### Update a user
PATCH http://localhost:3000/users/1
content-type: application/json

{
  "password": "shhhh"
}